# Generated by Django 5.1.1 on 2024-09-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itembarang_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembarang',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='itembarang',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
